# Generated by Django 3.2.3 on 2021-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(max_length=11)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_by', models.CharField(default=None, max_length=50)),
                ('transfered_to', models.CharField(default=None, max_length=50)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
