# Generated by Django 3.2.3 on 2021-05-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_System', '0002_alter_cutomers_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history',
        ),
    ]
