# Generated by Django 3.2.3 on 2021-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_System', '0003_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_by', models.CharField(default=None, max_length=50)),
                ('transfered_to', models.CharField(default=None, max_length=50)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
